# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95c43440561db4e0eae059af40e8c0ac64138e2c2fbfcc8e1cc6d8f9912dfe2362b59f9f700194a1309288b42fc87330e403d4b55adfa2bf45449956c95c8a0

test:
  secret_key_base: 637d171487089c27349642e64eda1a039587a119b2f504c4e6838b2782ff1f57ac9da6da7a10cb1f2b9199c6d85237b89b5ab4659b74d35455cc75b34566ff25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
